# action.yml
name: 'Chenyt26 Hello World'
description: 'Greet someone and record the time'
inputs:
  access_key:
    description: "The name of the storage account container these assets will be uploaded to"
    required: true
  secret_key:
    description: "The name of the directory you want to upload"
    required: true
  file_path:
    description: "The name of the directory you want to upload"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
